jenkins:
  deploy: true

  # Override subchart parameters
  # https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml
  master:
    image: openshift-4-jenkins
    tag: latest
    runAsUser: 1000530000
    fsGroup: 1000530000
    adminUser: Wfbk0gczanA8AWdAl4j
    adminPassword: pCQvT3@O#JM4M2Jx0Dl
    route:
      enabled: true
    installPlugins:
    - configuration-as-code:latest
    - openshift-client:latest
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
    JCasC:
      enabled: true
      defaultConfig: true
      configScripts:
        openshiftCredentials:
        credentials:
          system:
            domainCredentials:
            - credentials:
              - openShiftToken:
                  id: "system:serviceaccounts:<project>:<serviceaccount>"
                  scope: GLOBAL
                  secret: "{<secret>}"
  rbac:
    create: false

