
master:
  image: "registry.redhat.io/openshift4/ose-jenkins"
  imageTag: "4.2"

  # Used for label app.kubernetes.io/component
  componentName: "jenkins-master"

  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

  healthProbesReadinessTimeout: 5
  healthProbeReadinessPeriodSeconds: 10
  healthProbeReadinessFailureThreshold: 3
  healthProbeReadinessInitialDelay: 60