apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": build
spec:
  triggers:
  - type: ConfigChange
  source:
    type: Dockerfile
    dockerfile: |
      FROM jenkins/jenkins:lts
      USER root
      # Change directory permissions on default Jenkins image.
      # OpenShift runs containers as and arbitrary uid and uses group 0 for access
      # More information: https://docs.openshift.com/container-platform/4.2/openshift_images/create-images.html#images-create-guide-openshift_create-images
      RUN chown -R 1001:0 /usr/share/jenkins \
        && chown -R 1001:0 /var/jenkins_home
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: '{{ template "jenkins.fullname" . }}:latest'
status: